function skimgrinchscript(petdetcsv, intden, chambers, log, histo) %petdetpath, intdenpath, chambers#, log, histo
    %Import files declared by app
    %csv file are generated by imageJ scripts with specific formatting
    pd_opts = detectImportOptions(petdetcsv);
    pd = readmatrix(petdetcsv, pd_opts); %petdetective matrix
    id_opts = detectImportOptions(intden);
    id = readmatrix(intden, id_opts); %intden matrix
    sz = size(id);
    Max = max(id,[],'all'); %max value of intden (max min is to put every plot on same scale)
    min_id = id;
    min_id(:,1)=[]; %min value of intden such that 0-time end isnt considered
    Min = min(min_id,[],'all');
    clear figure(1)
    clear figure(2)
    figure(1)
    f1 = tiledlayout(8,20);
    %establish empty matrices
    cell_slope = [];
    all_slope = [];
    for i=1:chambers
		nexttile;
        if pd(i,4) == 0 %petdetective
            color = ('k.'); %black is k: no cell
        else 
            color = ('g.'); %green is g: cell present
        end
        if log == 1
            y_log = log10(id(:,i+1)); %convert intensity to log
            plot1 = plot(id(:,1), y_log, color); %plot log
		else
            plot1 = plot(id(:,1), id(:,i+1), color);
        end
        axis([0 sz(1) Min Max]) %x axis 0 to time max, y from min intensity to max intensity
        set(gca,'xtick',[],'ytick',[]); %removes axis labels (gca: get current axis) 160 axis labels is bad
        title(num2str(i)); %plot titles by iteration number
        if histo == 1
            xdata1 = get(plot1, 'xdata');
            ydata1 = get(plot1, 'ydata');
            xdata1 = xdata1(:);
            ydata1 = ydata1(:);
            fitResults1 = polyfit(xdata1,ydata1,1);
            slope1 = fitResults1(1,1);
            all_slope = [all_slope, slope1];
            if pd(i,4) == 1 %slope matrix from cells only
				cell_slope = [cell_slope, slope1];
            end
        end
    end
    tstr = "Timelapse results for " +chambers + " Chambers"; 
    tstr = tstr + newline + "(Fluorescence vs Time)";
    title(f1,tstr, 'FontWeight','bold');
    xstr = "Time" +newline + "(from 0 to "+sz(1)+" min)";
    xlabel(f1, xstr, 'FontWeight','bold');
    ylabel(f1, "Fluorescence Intensity (arb. unit)",'FontWeight', 'bold');
    if histo == 1
       f2 = figure(2);
       histogram(cell_slope);
              title('Cell Slope')
    xstr = "Slope (Fluorescence vs Time)";
    xlabel(f2, xstr, 'FontWeight','bold');
    ylabel(f2, "Quantity of Chambers",'FontWeight', 'bold');
    end
end

